# Generated by Django 2.2 on 2021-09-15 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goat_app', '0002_auto_20210913_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='blank', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='blank', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='hashpass',
            field=models.CharField(default='###', max_length=115),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='blank', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat1_id', models.IntegerField(default=0)),
                ('goat2_id', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='goat_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='GOAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('goat_id', models.IntegerField(default=0)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_fav', to='goat_app.User')),
            ],
        ),
    ]
