# Generated by Django 2.2 on 2021-08-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_added',
            field=models.DateTimeField(default=None),
        ),
    ]
