# Generated by Django 2.2 on 2021-08-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojos_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='email_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ninjas',
            name='years_old',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
