# Generated by Django 2.2 on 2021-09-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoptest_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
