# Generated by Django 2.2 on 2021-08-17 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest_prac_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='city',
            new_name='network',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='state',
        ),
        migrations.AddField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 1, 6, 14, 652417)),
        ),
    ]
