# Generated by Django 2.2 on 2021-08-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest_prac_app', '0002_auto_20210817_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
