# Generated by Django 2.2 on 2021-08-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest_prac_app', '0003_auto_20210817_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='desc',
            field=models.TextField(default=False),
        ),
    ]
