# Generated by Django 2.2 on 2021-08-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest_prac_app', '0004_shows_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='desc',
            field=models.TextField(default=None),
        ),
    ]
