# Generated by Django 2.2 on 2021-09-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GOATdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=55)),
                ('api_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.IntegerField(default=1000)),
                ('bet', models.IntegerField(default=0)),
                ('vote', models.CharField(max_length=155, null=True)),
                ('hashpass', models.CharField(max_length=115)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat1_id', models.IntegerField(default=0)),
                ('goat2_id', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='goat_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='GOAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=25)),
                ('api_id', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='goat_app.User')),
                ('favorite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_fav', to='goat_app.User')),
            ],
        ),
    ]
