# Generated by Django 2.2 on 2021-09-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goat_app', '0003_auto_20210915_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOAT_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('goat_id', models.IntegerField(default=0)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DB_fav', to='goat_app.User')),
            ],
        ),
    ]
