# Generated by Django 2.2 on 2021-09-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goat_app', '0004_goat_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GOAT_DB',
            new_name='GOATdb',
        ),
    ]
