# Generated by Django 2.2 on 2021-09-16 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goat_app', '0006_remove_goatdb_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='goat_app.User'),
        ),
    ]
