# Generated by Django 2.2 on 2021-09-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goat_app', '0007_goat_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_fav', to='goat_app.User'),
        ),
    ]
