# Generated by Django 2.2 on 2021-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_app', '0008_auto_20210916_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bet',
            field=models.IntegerField(default=0),
        ),
    ]
