# Generated by Django 2.2 on 2021-09-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_app', '0009_user_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
