# Generated by Django 2.2 on 2021-09-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_app', '0011_auto_20210916_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='full_name',
            field=models.CharField(default='blank', max_length=25),
            preserve_default=False,
        ),
    ]
